export const skillGroups = {
  programming: ["Python", "Java", "C/C++", "SQL", "JavaScript", "PHP", "R"],
  web: ["React", "Next.js", "Laravel", "Flask", "Django", "REST", "Firebase", "Supabase", "Docker"],
  dataAi: [
    "Pandas",
    "NumPy",
    "Scikit-learn",
    "TensorFlow",
    "Keras",
    "PyTorch",
    "NLTK",
    "SpaCy",
    "Transformers",
    "VAE",
    "Diffusion Models",
    "CRISP-DM",
  ],
  dataEngineering: ["FastAPI", "MLflow", "Elasticsearch", "Kibana", "PostgreSQL (pgVector)", "OpenSearch", "Docker"],
  tools: [
    "Git/GitHub",
    "VS Code",
    "Postman",
    "Airtable",
    "Trello",
    "Tableau",
    "Excel",
    "Oracle DB",
    "Arduino IDE",
    "Google Workspace",
  ],
} as const;
